-- agent-history squashed baseline schema (schema_version 1).
-- Generated by pg_dump --schema-only from the catalogue schema and numbered migrations.
-- Apply once to a database without table ah.meta; bundled migrations are already present.
-- Do not edit by hand.

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_extension WHERE extname = 'vector') THEN CREATE EXTENSION vector; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_extension WHERE extname = 'pg_search') THEN CREATE EXTENSION pg_search; END IF; END $$;

DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_namespace WHERE nspname = 'ah') THEN CREATE SCHEMA ah; END IF; END $$;

CREATE TABLE ah.artifact (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    call_uid text,
    ts timestamp with time zone NOT NULL,
    kind text NOT NULL,
    action text NOT NULL,
    path text NOT NULL,
    display_name text,
    evidence_type text NOT NULL,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
);

CREATE SEQUENCE ah.artifact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.artifact_id_seq OWNED BY ah.artifact.id;

CREATE TABLE ah.attachment (
    id bigint NOT NULL,
    agent text NOT NULL,
    attachment_uid text NOT NULL,
    session_id bigint NOT NULL,
    namespace text NOT NULL,
    turn_key text,
    ts timestamp with time zone NOT NULL,
    kind text NOT NULL,
    source text NOT NULL,
    event_uid text,
    call_uid text,
    mime text,
    file_name text,
    size_bytes bigint,
    text text,
    text_sha256 text,
    detail jsonb,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
);

CREATE SEQUENCE ah.attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.attachment_id_seq OWNED BY ah.attachment.id;

CREATE TABLE ah.backlog_task (
    task_key text NOT NULL,
    repo_slug text NOT NULL,
    context text NOT NULL,
    title text,
    status text,
    priority text,
    labels text[],
    project text,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    seen_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ah.change_log (
    seq bigint NOT NULL,
    refresh_id bigint NOT NULL,
    agent text NOT NULL,
    session_uid text NOT NULL,
    agent_id text DEFAULT ''::text NOT NULL,
    kind text NOT NULL,
    at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT change_log_kind_check CHECK ((kind = ANY (ARRAY['content'::text, 'orchestration'::text, 'rebuild'::text])))
);

COMMENT ON TABLE ah.change_log IS 'Monotonic per-refresh change feed keyed by session natural key; resume from the last seen seq. Never truncated by rebuild (a rebuild writes one kind=rebuild row with session_uid ''*''). Pruned after 90 days.';

CREATE SEQUENCE ah.change_log_seq_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.change_log_seq_seq OWNED BY ah.change_log.seq;

CREATE TABLE ah.chunk (
    id bigint NOT NULL,
    message_id bigint,
    summary_id bigint,
    session_id bigint,
    namespace text NOT NULL,
    ts timestamp with time zone NOT NULL,
    chunk_no smallint NOT NULL,
    char_start integer NOT NULL,
    char_end integer NOT NULL,
    source_sha256 text NOT NULL,
    model text NOT NULL,
    input_sha256 text NOT NULL,
    tool_call_id bigint,
    tool_op_id bigint,
    CONSTRAINT chunk_one_source CHECK ((num_nonnulls(message_id, summary_id, tool_call_id, tool_op_id) = 1))
);

COMMENT ON COLUMN ah.chunk.source_sha256 IS 'message.content_sha256, session_summary.journal_revision_id, or sha256 hex of tool_call/tool_op.error_excerpt';

CREATE SEQUENCE ah.chunk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.chunk_id_seq OWNED BY ah.chunk.id;

CREATE TABLE ah.ci_run (
    run_id bigint NOT NULL,
    repo_slug text NOT NULL,
    context text NOT NULL,
    head_sha text NOT NULL,
    workflow text,
    event text,
    status text,
    conclusion text,
    attempt integer,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    seen_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ah.compaction (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    ts timestamp with time zone NOT NULL,
    trigger text,
    pre_tokens bigint,
    post_tokens bigint,
    duration_ms integer,
    dropped_tokens bigint,
    window_number integer,
    window_id text,
    previous_window_id text,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
);

CREATE SEQUENCE ah.compaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.compaction_id_seq OWNED BY ah.compaction.id;

CREATE TABLE ah.cost_state (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    ts timestamp with time zone NOT NULL,
    total_cost_usd numeric,
    api_duration_ms bigint,
    api_duration_no_retry_ms bigint,
    tool_duration_ms bigint,
    total_duration_ms bigint,
    lines_added integer,
    lines_removed integer,
    model_usage jsonb,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    start_time timestamp with time zone
);

COMMENT ON COLUMN ah.cost_state.start_time IS 'Claude process start (cost-state startTime). Totals cover llm_call rows with ts >= start_time only.';

CREATE SEQUENCE ah.cost_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.cost_state_id_seq OWNED BY ah.cost_state.id;

CREATE TABLE ah.dirty_session (
    session_id bigint NOT NULL,
    marked_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ah.embed_failure (
    model text NOT NULL,
    input_sha256 text NOT NULL,
    message_id bigint,
    summary_id bigint,
    attempts integer DEFAULT 1 NOT NULL,
    last_error text,
    last_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ah.embedding (
    model text NOT NULL,
    input_sha256 text NOT NULL,
    embedding public.halfvec(1024) NOT NULL,
    input_tokens integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ah.file_touch (
    id bigint NOT NULL,
    agent text NOT NULL,
    touch_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    ts timestamp with time zone NOT NULL,
    path text NOT NULL,
    op text NOT NULL,
    tool text NOT NULL,
    call_uid text,
    item_uid text,
    lines_added integer,
    lines_removed integer,
    move_from text,
    repo_id bigint,
    repo_path text,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    CONSTRAINT file_touch_op_check CHECK ((op = ANY (ARRAY['read'::text, 'create'::text, 'edit'::text, 'delete'::text, 'move'::text])))
);

CREATE SEQUENCE ah.file_touch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.file_touch_id_seq OWNED BY ah.file_touch.id;

CREATE TABLE ah.git_commit (
    repo_slug text NOT NULL,
    sha text NOT NULL,
    context text NOT NULL,
    committed_at timestamp with time zone NOT NULL,
    subject text,
    parent_count smallint,
    files_changed integer,
    insertions integer,
    deletions integer,
    reverts_sha text,
    on_default boolean,
    seen_at timestamp with time zone DEFAULT now() NOT NULL,
    author_is_owner boolean
);

CREATE TABLE ah.git_commit_file (
    repo_slug text NOT NULL,
    sha text NOT NULL,
    path text NOT NULL,
    change character(1) NOT NULL,
    old_path text,
    insertions integer,
    deletions integer
);

CREATE TABLE ah.git_event (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    call_uid text,
    ts timestamp with time zone NOT NULL,
    cwd text,
    repo_id bigint,
    op text NOT NULL,
    branch text,
    sha_short text,
    pr_number integer,
    pr_action text,
    pr_url text,
    pr_repo text,
    remote_url text,
    evidence text NOT NULL,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    CONSTRAINT git_event_op_check CHECK ((op = ANY (ARRAY['commit'::text, 'cherry_pick'::text, 'push'::text, 'pr'::text, 'rebase'::text, 'merge'::text, 'session_start'::text])))
);

CREATE SEQUENCE ah.git_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.git_event_id_seq OWNED BY ah.git_event.id;

CREATE TABLE ah.hook_event (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    call_uid text,
    ts timestamp with time zone NOT NULL,
    hook_event text,
    outcome text,
    hook_name text,
    command_sha256 text,
    exit_code integer,
    duration_ms integer,
    timed_out boolean,
    prevented_continuation boolean,
    output_bytes integer,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
);

CREATE SEQUENCE ah.hook_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.hook_event_id_seq OWNED BY ah.hook_event.id;

CREATE TABLE ah.installed_feature (
    machine text NOT NULL,
    home text NOT NULL,
    namespace text NOT NULL,
    kind text NOT NULL,
    name text NOT NULL,
    source text,
    enabled boolean DEFAULT true NOT NULL,
    first_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    seen_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT installed_feature_kind_check CHECK ((kind = ANY (ARRAY['skill'::text, 'plugin'::text, 'mcp_server'::text])))
);

CREATE TABLE ah.lane (
    id bigint NOT NULL,
    loop_run_id bigint NOT NULL,
    session_id bigint NOT NULL,
    lane_name text,
    role text,
    link_method text NOT NULL,
    return_status text,
    lane_return jsonb
);

CREATE SEQUENCE ah.lane_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.lane_id_seq OWNED BY ah.lane.id;

CREATE TABLE ah.llm_call (
    id bigint NOT NULL,
    agent text NOT NULL,
    response_id text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    ts timestamp with time zone NOT NULL,
    model text,
    request_id text,
    stop_reason text,
    input_uncached bigint,
    cache_read bigint,
    cache_write_5m bigint,
    cache_write_1h bigint,
    output bigint,
    reasoning bigint,
    context_tokens bigint GENERATED ALWAYS AS ((((COALESCE(input_uncached, (0)::bigint) + COALESCE(cache_read, (0)::bigint)) + COALESCE(cache_write_5m, (0)::bigint)) + COALESCE(cache_write_1h, (0)::bigint))) STORED,
    context_window bigint,
    web_search_requests integer,
    web_fetch_requests integer,
    service_tier text,
    speed text,
    effort text,
    is_api_error boolean DEFAULT false NOT NULL,
    error_kind text,
    api_error_status integer,
    is_sidechain boolean DEFAULT false NOT NULL,
    line_count integer,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
)
WITH (autovacuum_vacuum_scale_factor='0.02');

CREATE SEQUENCE ah.llm_call_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.llm_call_id_seq OWNED BY ah.llm_call.id;

CREATE TABLE ah.loop_run (
    id bigint NOT NULL,
    launch_uid text NOT NULL,
    root_session_id bigint,
    status text DEFAULT 'resolved'::text NOT NULL,
    repo_slug text,
    campaign_slug text,
    loop_number integer,
    naming text,
    mode text,
    report_path text,
    goal_path text,
    launch_path text,
    launch_sha256 text,
    launch_ts timestamp with time zone,
    end_ts timestamp with time zone,
    end_evidence text,
    budget_s integer
);

CREATE SEQUENCE ah.loop_run_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.loop_run_id_seq OWNED BY ah.loop_run.id;

CREATE TABLE ah.message (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    namespace text NOT NULL,
    profile text NOT NULL,
    turn_key text,
    ts timestamp with time zone NOT NULL,
    role text NOT NULL,
    message_class text NOT NULL,
    model text,
    is_sidechain boolean DEFAULT false NOT NULL,
    text text NOT NULL,
    content_sha256 text NOT NULL,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    byte_length integer NOT NULL,
    line_number bigint,
    prompt_origin text,
    detail jsonb,
    text_sha256 text,
    seq bigint,
    raw_record_origin text,
    CONSTRAINT message_message_class_check CHECK ((message_class = ANY (ARRAY['human_prompt'::text, 'queued_prompt'::text, 'assistant_text'::text, 'subagent_brief'::text, 'subagent_report'::text, 'compaction_summary'::text, 'task_notification_summary'::text, 'reasoning'::text, 'system_prompt'::text, 'system_reminder'::text, 'context_injection'::text, 'hook_output'::text, 'command_expansion'::text, 'skill_body'::text, 'local_command_output'::text, 'agent_message'::text, 'interrupt_marker'::text]))),
    CONSTRAINT message_prompt_origin_check CHECK ((prompt_origin = ANY (ARRAY['typed'::text, 'pasted'::text, 'slash_command'::text, 'skill'::text, 'hook'::text, 'local_command'::text, 'launch_message'::text, 'compaction_continuation'::text, 'agent_message'::text, 'interrupt'::text, 'other'::text]))),
    CONSTRAINT message_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])))
)
WITH (autovacuum_vacuum_scale_factor='0', autovacuum_vacuum_threshold='100000');

COMMENT ON COLUMN ah.message.content_sha256 IS 'sha256 hex of message.text exactly as stored (UTF-8 bytes, after the loader drops NUL characters). Equal to text_sha256.';

COMMENT ON COLUMN ah.message.text_sha256 IS 'sha256 hex of message.text as stored (UTF-8 bytes): encode(sha256(convert_to(text, ''UTF8'')), ''hex'').';

COMMENT ON COLUMN ah.message.seq IS 'Per-session order across message, tool_call, tool_op (tool_io shares its call/op seq). Deterministic from source position, so stable across rebuild; new rows append.';

CREATE SEQUENCE ah.message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.message_id_seq OWNED BY ah.message.id;

CREATE TABLE ah.meta (
    key text NOT NULL,
    value text NOT NULL
);

CREATE TABLE ah.model_pricing (
    model text NOT NULL,
    effective_from date NOT NULL,
    input_per_mtok numeric,
    cached_input_per_mtok numeric,
    cache_write_per_mtok numeric,
    output_per_mtok numeric,
    cache_write_1h_per_mtok numeric,
    source text
);

CREATE TABLE ah.parse_issue (
    id bigint NOT NULL,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    line_number bigint,
    kind text NOT NULL,
    detail text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE ah.parse_issue_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.parse_issue_id_seq OWNED BY ah.parse_issue.id;

CREATE TABLE ah.permission_log (
    machine text NOT NULL,
    home text NOT NULL,
    namespace text NOT NULL,
    ts timestamp with time zone NOT NULL,
    line_hash text NOT NULL,
    tool_name text,
    cmd_verb text,
    reason text,
    is_subagent boolean
);

CREATE TABLE ah.pi_run_response (
    run_id text NOT NULL,
    response_id text NOT NULL,
    agent_type text,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
);

CREATE TABLE ah.rate_limit_sample (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    ts timestamp with time zone NOT NULL,
    window_kind text NOT NULL,
    limit_id text,
    limit_name text,
    plan_type text,
    used_percent numeric,
    window_minutes integer,
    resets_at timestamp with time zone,
    reached_type text,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
);

CREATE SEQUENCE ah.rate_limit_sample_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.rate_limit_sample_id_seq OWNED BY ah.rate_limit_sample.id;

CREATE TABLE ah.record_type_seen (
    agent text NOT NULL,
    record_type text NOT NULL,
    subtype text DEFAULT ''::text NOT NULL,
    key_set text,
    first_seen timestamp with time zone NOT NULL,
    last_seen timestamp with time zone NOT NULL,
    seen_count bigint DEFAULT 0 NOT NULL,
    cli_version text
);

CREATE SEQUENCE ah.refresh_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE ah.refresh_log (
    refresh_id bigint NOT NULL,
    kind text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    sessions_changed integer,
    ok boolean,
    CONSTRAINT refresh_log_kind_check CHECK ((kind = ANY (ARRAY['refresh'::text, 'rebuild'::text])))
);

CREATE TABLE ah.repo (
    id bigint NOT NULL,
    local_root text NOT NULL,
    slug text NOT NULL,
    remote_url text
);

CREATE SEQUENCE ah.repo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.repo_id_seq OWNED BY ah.repo.id;

CREATE TABLE ah.session (
    id bigint NOT NULL,
    agent text NOT NULL,
    session_uid text NOT NULL,
    agent_id text DEFAULT ''::text NOT NULL,
    is_stub boolean DEFAULT true NOT NULL,
    namespace text,
    profile text,
    machine text,
    is_subagent boolean DEFAULT false NOT NULL,
    root_session_uid text,
    parent_session_uid text,
    parent_agent_id text,
    parent_call_uid text,
    root_session_id bigint,
    parent_session_id bigint,
    spawn_kind text,
    spawn_depth integer,
    agent_type text,
    agent_type_source text,
    agent_role text,
    agent_path text,
    agent_nickname text,
    forked_from_uid text,
    workflow_id text,
    title text,
    custom_title text,
    cwd text,
    repo_id bigint,
    git_branch text,
    git_commit_start text,
    git_remote_url text,
    cli_version_first text,
    cli_version_last text,
    entrypoint text,
    model_provider text,
    thread_source text,
    history_mode text,
    first_event_at timestamp with time zone,
    last_event_at timestamp with time zone,
    first_human_at timestamp with time zone,
    last_human_at timestamp with time zone,
    inherited_skipped bigint DEFAULT 0 NOT NULL,
    loop_run_id bigint,
    lane_id bigint,
    loop_link_method text,
    continued_from_session_id bigint,
    continuation_kind text,
    first_prompt_event_uid text,
    first_prompt_at timestamp with time zone,
    orchestration_kind text,
    orchestration_root_session_id bigint,
    is_orchestration_descendant boolean DEFAULT false NOT NULL,
    orchestration_evidence text,
    content_changed_at timestamp with time zone,
    CONSTRAINT session_agent_check CHECK ((agent = ANY (ARRAY['claude'::text, 'codex'::text, 'pi'::text]))),
    CONSTRAINT session_agent_type_source_check CHECK ((agent_type_source = ANY (ARRAY['explicit'::text, 'default'::text]))),
    CONSTRAINT session_orchestration_kind_check CHECK ((orchestration_kind = ANY (ARRAY['none'::text, 'loop_root'::text, 'wave_root'::text, 'fanout_root'::text, 'workflow_root'::text, 'lane'::text, 'poller'::text, 'reviewer'::text, 'subagent'::text, 'other'::text])))
);

CREATE TABLE ah.session_continuation (
    id bigint NOT NULL,
    agent text NOT NULL,
    child_uid text NOT NULL,
    parent_uid text NOT NULL,
    kind text NOT NULL,
    session_id bigint NOT NULL,
    ts timestamp with time zone NOT NULL,
    evidence text NOT NULL,
    child_session_id bigint,
    parent_session_id bigint,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    CONSTRAINT session_continuation_kind_check CHECK ((kind = ANY (ARRAY['resume'::text, 'fork'::text, 'compaction_continuation'::text, 'clear'::text, 'other'::text])))
);

CREATE SEQUENCE ah.session_continuation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.session_continuation_id_seq OWNED BY ah.session_continuation.id;

CREATE TABLE ah.session_embedding (
    session_id bigint NOT NULL,
    model text NOT NULL,
    embedding public.halfvec(1024) NOT NULL,
    chunk_count integer NOT NULL,
    chunk_max_id bigint NOT NULL,
    computed_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ah.session_event (
    id bigint NOT NULL,
    agent text NOT NULL,
    event_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    ts timestamp with time zone NOT NULL,
    kind text NOT NULL,
    value text,
    detail jsonb,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL
);

CREATE SEQUENCE ah.session_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.session_event_id_seq OWNED BY ah.session_event.id;

CREATE SEQUENCE ah.session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.session_id_seq OWNED BY ah.session.id;

CREATE TABLE ah.session_rollup (
    session_id bigint NOT NULL,
    computed_at timestamp with time zone NOT NULL,
    turns_human integer,
    turns_other integer,
    messages integer,
    llm_calls integer,
    input_uncached bigint,
    cache_read bigint,
    cache_write bigint,
    output bigint,
    reasoning bigint,
    peak_context_tokens bigint,
    tool_calls integer,
    tool_errors integer,
    tool_denials integer,
    tool_interrupts integer,
    subagents integer,
    compactions integer,
    commits integer,
    pushes integer,
    api_errors integer,
    interrupts integer,
    models text[],
    cli_versions text[],
    duration_s bigint,
    claude_cost_usd numeric,
    snapshot_calls integer,
    active_s bigint,
    human_prompts integer,
    tool_calls_by_family jsonb,
    error_count integer,
    priced_cost_usd numeric,
    repo_slug text,
    git_branch text,
    final_turn_status text,
    content_fingerprint text
);

COMMENT ON COLUMN ah.session_rollup.snapshot_calls IS 'Claude calls with no stop_reason: usage is the streamed snapshot, so output is a lower bound. NULL for Codex.';

CREATE TABLE ah.session_summary (
    id bigint NOT NULL,
    journal_conversation_id text NOT NULL,
    session_id bigint,
    journal_revision_id text NOT NULL,
    namespace text NOT NULL,
    title text,
    objective text,
    narrative text,
    outcomes jsonb,
    unfinished jsonb,
    classification text,
    project text,
    model text,
    analysed_at timestamp with time zone NOT NULL,
    agent text,
    session_uid text,
    agent_id text,
    app_instance_id text
);

CREATE SEQUENCE ah.session_summary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.session_summary_id_seq OWNED BY ah.session_summary.id;

CREATE TABLE ah.session_topic (
    journal_conversation_id text NOT NULL,
    topic text NOT NULL,
    session_id bigint,
    provenance text,
    confidence numeric,
    session_agent text,
    session_uid text,
    session_agent_id text
);

CREATE TABLE ah.source_file (
    id bigint NOT NULL,
    rel_path text NOT NULL,
    namespace text NOT NULL,
    agent text NOT NULL,
    profile text NOT NULL,
    machine text,
    file_role text NOT NULL,
    logical_uid text,
    tier text NOT NULL,
    available_hot boolean DEFAULT false NOT NULL,
    available_cold boolean DEFAULT false NOT NULL,
    size_bytes bigint DEFAULT 0 NOT NULL,
    mtime_ns bigint DEFAULT 0 NOT NULL,
    indexed_offset bigint DEFAULT 0 NOT NULL,
    line_count bigint DEFAULT 0 NOT NULL,
    checkpoint_start bigint DEFAULT 0 NOT NULL,
    checkpoint_sha256 text,
    head_sha256 text,
    parser_version text DEFAULT ''::text NOT NULL,
    parser_state jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    rewrite_count integer DEFAULT 0 NOT NULL,
    indexed_at timestamp with time zone,
    CONSTRAINT source_file_agent_check CHECK ((agent = ANY (ARRAY['claude'::text, 'codex'::text, 'pi'::text]))),
    CONSTRAINT source_file_file_role_check CHECK ((file_role = ANY (ARRAY['main'::text, 'subagent'::text, 'workflow_agent'::text, 'workflow_journal'::text, 'pi_artifact'::text]))),
    CONSTRAINT source_file_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'indexed'::text, 'partial'::text, 'unavailable'::text, 'error'::text]))),
    CONSTRAINT source_file_tier_check CHECK ((tier = ANY (ARRAY['hot'::text, 'cold'::text])))
);

CREATE SEQUENCE ah.source_file_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.source_file_id_seq OWNED BY ah.source_file.id;

CREATE TABLE ah.subagent_spawn (
    id bigint NOT NULL,
    agent text NOT NULL,
    spawn_uid text NOT NULL,
    parent_session_id bigint NOT NULL,
    turn_key text,
    child_session_uid text,
    child_agent_id text,
    child_task_name text,
    child_session_id bigint,
    spawned_at timestamp with time zone,
    requested_type text,
    requested_type_source text,
    requested_model text,
    resolved_model text,
    reasoning_effort text,
    background boolean,
    fork_scope text,
    isolation text,
    name text,
    description text,
    launch_status text,
    completion_status text,
    completed_at timestamp with time zone,
    reported_tokens bigint,
    reported_tool_uses integer,
    reported_duration_ms bigint,
    workflow_id text,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    CONSTRAINT subagent_spawn_requested_type_source_check CHECK ((requested_type_source = ANY (ARRAY['explicit'::text, 'default'::text])))
);

CREATE SEQUENCE ah.subagent_spawn_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.subagent_spawn_id_seq OWNED BY ah.subagent_spawn.id;

CREATE TABLE ah.task_prefix (
    prefix text NOT NULL,
    repo_slug text NOT NULL,
    context text NOT NULL,
    zero_pad smallint,
    seen_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE ah.task_ref (
    session_id bigint NOT NULL,
    task_key text NOT NULL,
    first_ts timestamp with time zone NOT NULL,
    last_ts timestamp with time zone NOT NULL,
    mentions integer NOT NULL,
    in_human boolean DEFAULT false NOT NULL,
    in_brief boolean DEFAULT false NOT NULL
);

CREATE TABLE ah.tool_call (
    id bigint NOT NULL,
    agent text NOT NULL,
    call_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    response_id text,
    tool_name text NOT NULL,
    tool_family text,
    mcp_server text,
    mcp_tool text,
    codex_namespace text,
    started_at timestamp with time zone,
    ended_at timestamp with time zone,
    duration_ms integer,
    input_bytes integer,
    output_bytes integer,
    persisted_output_bytes bigint,
    outcome text,
    is_error boolean,
    exit_code integer,
    denial_kind text,
    interrupted boolean,
    timed_out boolean,
    background boolean,
    attribution_skill text,
    attribution_plugin text,
    meta jsonb,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    error_class text,
    error_excerpt text,
    seq bigint,
    CONSTRAINT tool_call_outcome_check CHECK ((outcome = ANY (ARRAY['ok'::text, 'error'::text, 'denied'::text, 'interrupted'::text, 'timeout'::text, 'no_result'::text])))
)
WITH (autovacuum_vacuum_scale_factor='0.02');

CREATE SEQUENCE ah.tool_call_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.tool_call_id_seq OWNED BY ah.tool_call.id;

CREATE TABLE ah.tool_io (
    id bigint NOT NULL,
    agent text NOT NULL,
    io_uid text NOT NULL,
    session_id bigint NOT NULL,
    namespace text NOT NULL,
    profile text NOT NULL,
    kind text NOT NULL,
    tool_name text,
    call_uid text,
    item_uid text,
    turn_key text,
    ts timestamp with time zone NOT NULL,
    output_at timestamp with time zone,
    input_text text,
    input_bytes integer,
    input_sha256 text,
    input_truncated boolean,
    output_text text,
    output_bytes integer,
    output_sha256 text,
    output_truncated boolean,
    stdout_text text,
    stdout_bytes integer,
    stdout_sha256 text,
    stderr_text text,
    stderr_bytes integer,
    stderr_sha256 text,
    result_json text,
    result_bytes integer,
    result_sha256 text,
    output_parts jsonb,
    seq bigint,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    output_byte_offset bigint,
    CONSTRAINT tool_io_kind_check CHECK ((kind = ANY (ARRAY['call'::text, 'op'::text])))
)
WITH (autovacuum_vacuum_scale_factor='0.02');

COMMENT ON TABLE ah.tool_io IS 'Full tool input and output (Claude tool_use/tool_result, Codex calls and executed ops). *_bytes are UTF-8 octet lengths and *_sha256 the sha256 hex of each stored text column. Binary parts are metadata only.';

CREATE SEQUENCE ah.tool_io_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.tool_io_id_seq OWNED BY ah.tool_io.id;

CREATE TABLE ah.tool_op (
    id bigint NOT NULL,
    agent text NOT NULL,
    item_uid text NOT NULL,
    session_id bigint NOT NULL,
    turn_key text,
    item_type text NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    duration_ms integer,
    status text,
    exit_code integer,
    exec_source text,
    cmd_verb text,
    parsed_cmd_types text[],
    mcp_server text,
    mcp_tool text,
    is_error boolean,
    output_bytes integer,
    file_count integer,
    call_uid text,
    link_method text,
    source_id bigint NOT NULL,
    byte_offset bigint NOT NULL,
    error_class text,
    error_excerpt text,
    seq bigint
);

CREATE SEQUENCE ah.tool_op_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.tool_op_id_seq OWNED BY ah.tool_op.id;

CREATE TABLE ah.turn (
    id bigint NOT NULL,
    session_id bigint NOT NULL,
    turn_key text NOT NULL,
    origin text,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    duration_ms integer,
    ttft_ms integer,
    status text,
    abort_reason text,
    model text,
    effort text,
    permission_mode text,
    approval_policy text,
    sandbox_type text,
    collaboration_mode text,
    context_window bigint,
    message_count integer,
    source_id bigint,
    byte_offset bigint
);

CREATE SEQUENCE ah.turn_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE ah.turn_id_seq OWNED BY ah.turn.id;

ALTER TABLE ONLY ah.artifact ALTER COLUMN id SET DEFAULT nextval('ah.artifact_id_seq'::regclass);

ALTER TABLE ONLY ah.attachment ALTER COLUMN id SET DEFAULT nextval('ah.attachment_id_seq'::regclass);

ALTER TABLE ONLY ah.change_log ALTER COLUMN seq SET DEFAULT nextval('ah.change_log_seq_seq'::regclass);

ALTER TABLE ONLY ah.chunk ALTER COLUMN id SET DEFAULT nextval('ah.chunk_id_seq'::regclass);

ALTER TABLE ONLY ah.compaction ALTER COLUMN id SET DEFAULT nextval('ah.compaction_id_seq'::regclass);

ALTER TABLE ONLY ah.cost_state ALTER COLUMN id SET DEFAULT nextval('ah.cost_state_id_seq'::regclass);

ALTER TABLE ONLY ah.file_touch ALTER COLUMN id SET DEFAULT nextval('ah.file_touch_id_seq'::regclass);

ALTER TABLE ONLY ah.git_event ALTER COLUMN id SET DEFAULT nextval('ah.git_event_id_seq'::regclass);

ALTER TABLE ONLY ah.hook_event ALTER COLUMN id SET DEFAULT nextval('ah.hook_event_id_seq'::regclass);

ALTER TABLE ONLY ah.lane ALTER COLUMN id SET DEFAULT nextval('ah.lane_id_seq'::regclass);

ALTER TABLE ONLY ah.llm_call ALTER COLUMN id SET DEFAULT nextval('ah.llm_call_id_seq'::regclass);

ALTER TABLE ONLY ah.loop_run ALTER COLUMN id SET DEFAULT nextval('ah.loop_run_id_seq'::regclass);

ALTER TABLE ONLY ah.message ALTER COLUMN id SET DEFAULT nextval('ah.message_id_seq'::regclass);

ALTER TABLE ONLY ah.parse_issue ALTER COLUMN id SET DEFAULT nextval('ah.parse_issue_id_seq'::regclass);

ALTER TABLE ONLY ah.rate_limit_sample ALTER COLUMN id SET DEFAULT nextval('ah.rate_limit_sample_id_seq'::regclass);

ALTER TABLE ONLY ah.repo ALTER COLUMN id SET DEFAULT nextval('ah.repo_id_seq'::regclass);

ALTER TABLE ONLY ah.session ALTER COLUMN id SET DEFAULT nextval('ah.session_id_seq'::regclass);

ALTER TABLE ONLY ah.session_continuation ALTER COLUMN id SET DEFAULT nextval('ah.session_continuation_id_seq'::regclass);

ALTER TABLE ONLY ah.session_event ALTER COLUMN id SET DEFAULT nextval('ah.session_event_id_seq'::regclass);

ALTER TABLE ONLY ah.session_summary ALTER COLUMN id SET DEFAULT nextval('ah.session_summary_id_seq'::regclass);

ALTER TABLE ONLY ah.source_file ALTER COLUMN id SET DEFAULT nextval('ah.source_file_id_seq'::regclass);

ALTER TABLE ONLY ah.subagent_spawn ALTER COLUMN id SET DEFAULT nextval('ah.subagent_spawn_id_seq'::regclass);

ALTER TABLE ONLY ah.tool_call ALTER COLUMN id SET DEFAULT nextval('ah.tool_call_id_seq'::regclass);

ALTER TABLE ONLY ah.tool_io ALTER COLUMN id SET DEFAULT nextval('ah.tool_io_id_seq'::regclass);

ALTER TABLE ONLY ah.tool_op ALTER COLUMN id SET DEFAULT nextval('ah.tool_op_id_seq'::regclass);

ALTER TABLE ONLY ah.turn ALTER COLUMN id SET DEFAULT nextval('ah.turn_id_seq'::regclass);

ALTER TABLE ONLY ah.artifact
    ADD CONSTRAINT artifact_agent_event_uid_path_action_key UNIQUE (agent, event_uid, path, action);

ALTER TABLE ONLY ah.artifact
    ADD CONSTRAINT artifact_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.attachment
    ADD CONSTRAINT attachment_agent_attachment_uid_key UNIQUE (agent, attachment_uid);

ALTER TABLE ONLY ah.attachment
    ADD CONSTRAINT attachment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.backlog_task
    ADD CONSTRAINT backlog_task_pkey PRIMARY KEY (task_key);

ALTER TABLE ONLY ah.change_log
    ADD CONSTRAINT change_log_pkey PRIMARY KEY (seq);

ALTER TABLE ONLY ah.chunk
    ADD CONSTRAINT chunk_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.ci_run
    ADD CONSTRAINT ci_run_pkey PRIMARY KEY (run_id);

ALTER TABLE ONLY ah.compaction
    ADD CONSTRAINT compaction_agent_event_uid_key UNIQUE (agent, event_uid);

ALTER TABLE ONLY ah.compaction
    ADD CONSTRAINT compaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.cost_state
    ADD CONSTRAINT cost_state_agent_event_uid_key UNIQUE (agent, event_uid);

ALTER TABLE ONLY ah.cost_state
    ADD CONSTRAINT cost_state_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.dirty_session
    ADD CONSTRAINT dirty_session_pkey PRIMARY KEY (session_id);

ALTER TABLE ONLY ah.embed_failure
    ADD CONSTRAINT embed_failure_pkey PRIMARY KEY (model, input_sha256);

ALTER TABLE ONLY ah.embedding
    ADD CONSTRAINT embedding_pkey PRIMARY KEY (model, input_sha256);

ALTER TABLE ONLY ah.file_touch
    ADD CONSTRAINT file_touch_agent_touch_uid_key UNIQUE (agent, touch_uid);

ALTER TABLE ONLY ah.file_touch
    ADD CONSTRAINT file_touch_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.git_commit_file
    ADD CONSTRAINT git_commit_file_pkey PRIMARY KEY (repo_slug, sha, path);

ALTER TABLE ONLY ah.git_commit
    ADD CONSTRAINT git_commit_pkey PRIMARY KEY (repo_slug, sha);

ALTER TABLE ONLY ah.git_event
    ADD CONSTRAINT git_event_agent_event_uid_key UNIQUE (agent, event_uid);

ALTER TABLE ONLY ah.git_event
    ADD CONSTRAINT git_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.hook_event
    ADD CONSTRAINT hook_event_agent_event_uid_key UNIQUE (agent, event_uid);

ALTER TABLE ONLY ah.hook_event
    ADD CONSTRAINT hook_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.installed_feature
    ADD CONSTRAINT installed_feature_pkey PRIMARY KEY (machine, home, kind, name);

ALTER TABLE ONLY ah.lane
    ADD CONSTRAINT lane_loop_run_id_session_id_key UNIQUE (loop_run_id, session_id);

ALTER TABLE ONLY ah.lane
    ADD CONSTRAINT lane_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.llm_call
    ADD CONSTRAINT llm_call_agent_response_id_key UNIQUE (agent, response_id);

ALTER TABLE ONLY ah.llm_call
    ADD CONSTRAINT llm_call_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.loop_run
    ADD CONSTRAINT loop_run_launch_uid_key UNIQUE (launch_uid);

ALTER TABLE ONLY ah.loop_run
    ADD CONSTRAINT loop_run_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.message
    ADD CONSTRAINT message_agent_event_uid_key UNIQUE (agent, event_uid);

ALTER TABLE ONLY ah.message
    ADD CONSTRAINT message_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.meta
    ADD CONSTRAINT meta_pkey PRIMARY KEY (key);

ALTER TABLE ONLY ah.model_pricing
    ADD CONSTRAINT model_pricing_pkey PRIMARY KEY (model, effective_from);

ALTER TABLE ONLY ah.parse_issue
    ADD CONSTRAINT parse_issue_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.parse_issue
    ADD CONSTRAINT parse_issue_source_id_byte_offset_kind_key UNIQUE (source_id, byte_offset, kind);

ALTER TABLE ONLY ah.permission_log
    ADD CONSTRAINT permission_log_pkey PRIMARY KEY (machine, home, line_hash);

ALTER TABLE ONLY ah.pi_run_response
    ADD CONSTRAINT pi_run_response_pkey PRIMARY KEY (run_id, response_id, source_id);

ALTER TABLE ONLY ah.rate_limit_sample
    ADD CONSTRAINT rate_limit_sample_agent_event_uid_window_kind_key UNIQUE (agent, event_uid, window_kind);

ALTER TABLE ONLY ah.rate_limit_sample
    ADD CONSTRAINT rate_limit_sample_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.record_type_seen
    ADD CONSTRAINT record_type_seen_pkey PRIMARY KEY (agent, record_type, subtype);

ALTER TABLE ONLY ah.refresh_log
    ADD CONSTRAINT refresh_log_pkey PRIMARY KEY (refresh_id);

ALTER TABLE ONLY ah.repo
    ADD CONSTRAINT repo_local_root_key UNIQUE (local_root);

ALTER TABLE ONLY ah.repo
    ADD CONSTRAINT repo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.session
    ADD CONSTRAINT session_agent_session_uid_agent_id_key UNIQUE (agent, session_uid, agent_id);

ALTER TABLE ONLY ah.session_continuation
    ADD CONSTRAINT session_continuation_agent_child_uid_parent_uid_kind_key UNIQUE (agent, child_uid, parent_uid, kind);

ALTER TABLE ONLY ah.session_continuation
    ADD CONSTRAINT session_continuation_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.session_embedding
    ADD CONSTRAINT session_embedding_pkey PRIMARY KEY (session_id);

ALTER TABLE ONLY ah.session_event
    ADD CONSTRAINT session_event_agent_event_uid_kind_key UNIQUE (agent, event_uid, kind);

ALTER TABLE ONLY ah.session_event
    ADD CONSTRAINT session_event_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.session
    ADD CONSTRAINT session_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.session_rollup
    ADD CONSTRAINT session_rollup_pkey PRIMARY KEY (session_id);

ALTER TABLE ONLY ah.session_summary
    ADD CONSTRAINT session_summary_journal_conversation_id_key UNIQUE (journal_conversation_id);

ALTER TABLE ONLY ah.session_summary
    ADD CONSTRAINT session_summary_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.session_topic
    ADD CONSTRAINT session_topic_pkey PRIMARY KEY (journal_conversation_id, topic);

ALTER TABLE ONLY ah.source_file
    ADD CONSTRAINT source_file_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.source_file
    ADD CONSTRAINT source_file_rel_path_key UNIQUE (rel_path);

ALTER TABLE ONLY ah.subagent_spawn
    ADD CONSTRAINT subagent_spawn_agent_spawn_uid_key UNIQUE (agent, spawn_uid);

ALTER TABLE ONLY ah.subagent_spawn
    ADD CONSTRAINT subagent_spawn_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.task_prefix
    ADD CONSTRAINT task_prefix_pkey PRIMARY KEY (prefix);

ALTER TABLE ONLY ah.task_ref
    ADD CONSTRAINT task_ref_pkey PRIMARY KEY (session_id, task_key);

ALTER TABLE ONLY ah.tool_call
    ADD CONSTRAINT tool_call_agent_call_uid_key UNIQUE (agent, call_uid);

ALTER TABLE ONLY ah.tool_call
    ADD CONSTRAINT tool_call_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.tool_io
    ADD CONSTRAINT tool_io_agent_io_uid_key UNIQUE (agent, io_uid);

ALTER TABLE ONLY ah.tool_io
    ADD CONSTRAINT tool_io_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.tool_op
    ADD CONSTRAINT tool_op_agent_item_uid_key UNIQUE (agent, item_uid);

ALTER TABLE ONLY ah.tool_op
    ADD CONSTRAINT tool_op_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.turn
    ADD CONSTRAINT turn_pkey PRIMARY KEY (id);

ALTER TABLE ONLY ah.turn
    ADD CONSTRAINT turn_session_id_turn_key_key UNIQUE (session_id, turn_key);

CREATE INDEX artifact_path_idx ON ah.artifact USING btree (path);

CREATE INDEX artifact_session_idx ON ah.artifact USING btree (session_id, ts);

CREATE INDEX attachment_session_idx ON ah.attachment USING btree (session_id, ts);

CREATE INDEX change_log_at_idx ON ah.change_log USING btree (at);

CREATE INDEX change_log_session_idx ON ah.change_log USING btree (agent, session_uid, agent_id, seq);

CREATE INDEX chunk_input_idx ON ah.chunk USING btree (model, input_sha256);

CREATE UNIQUE INDEX chunk_message_uq ON ah.chunk USING btree (message_id, model, chunk_no) WHERE (message_id IS NOT NULL);

CREATE INDEX chunk_ns_ts_idx ON ah.chunk USING btree (namespace, ts);

CREATE INDEX chunk_session_idx ON ah.chunk USING btree (session_id) WHERE (message_id IS NOT NULL);

CREATE UNIQUE INDEX chunk_summary_uq ON ah.chunk USING btree (summary_id, model, chunk_no) WHERE (summary_id IS NOT NULL);

CREATE UNIQUE INDEX chunk_tool_call_uq ON ah.chunk USING btree (tool_call_id, model, chunk_no) WHERE (tool_call_id IS NOT NULL);

CREATE UNIQUE INDEX chunk_tool_op_uq ON ah.chunk USING btree (tool_op_id, model, chunk_no) WHERE (tool_op_id IS NOT NULL);

CREATE INDEX ci_run_sha_idx ON ah.ci_run USING btree (head_sha);

CREATE INDEX compaction_session_idx ON ah.compaction USING btree (session_id, ts);

CREATE INDEX cost_state_session_idx ON ah.cost_state USING btree (session_id, ts);

CREATE INDEX file_touch_path_idx ON ah.file_touch USING btree (path text_pattern_ops);

CREATE INDEX file_touch_repo_idx ON ah.file_touch USING btree (repo_id, repo_path);

CREATE INDEX file_touch_session_idx ON ah.file_touch USING btree (session_id, ts);

CREATE INDEX git_commit_file_path_idx ON ah.git_commit_file USING btree (path text_pattern_ops);

CREATE INDEX git_commit_repo_idx ON ah.git_commit USING btree (repo_slug, committed_at);

CREATE INDEX git_commit_reverts_idx ON ah.git_commit USING btree (reverts_sha);

CREATE INDEX git_commit_sha_idx ON ah.git_commit USING btree (sha text_pattern_ops);

CREATE INDEX git_event_session_idx ON ah.git_event USING btree (session_id, ts);

CREATE INDEX git_event_sha_idx ON ah.git_event USING btree (sha_short);

CREATE INDEX hook_event_session_idx ON ah.hook_event USING btree (session_id, ts);

CREATE INDEX llm_call_session_idx ON ah.llm_call USING btree (session_id, ts);

CREATE INDEX llm_call_ts_idx ON ah.llm_call USING btree (ts);

CREATE INDEX loop_run_ts_idx ON ah.loop_run USING btree (launch_ts);

CREATE INDEX message_seq_idx ON ah.message USING btree (session_id, seq);

CREATE INDEX message_session_idx ON ah.message USING btree (session_id, ts);

CREATE INDEX message_ts_idx ON ah.message USING btree (ts);

CREATE INDEX pi_run_response_response_idx ON ah.pi_run_response USING btree (response_id);

CREATE INDEX rate_limit_ts_idx ON ah.rate_limit_sample USING btree (ts);

CREATE INDEX session_changed_idx ON ah.session USING btree (content_changed_at);

CREATE INDEX session_embedding_hnsw_idx ON ah.session_embedding USING hnsw (embedding public.halfvec_cosine_ops);

CREATE INDEX session_event_kind_idx ON ah.session_event USING btree (kind, ts);

CREATE INDEX session_event_session_idx ON ah.session_event USING btree (session_id, ts);

CREATE INDEX session_last_idx ON ah.session USING btree (last_event_at, namespace);

CREATE INDEX session_loop_idx ON ah.session USING btree (loop_run_id);

CREATE INDEX session_orch_root_idx ON ah.session USING btree (orchestration_root_session_id);

CREATE INDEX session_parent_idx ON ah.session USING btree (parent_session_id);

CREATE INDEX session_parent_uid_idx ON ah.session USING btree (agent, parent_session_uid);

CREATE INDEX session_root_idx ON ah.session USING btree (root_session_id);

CREATE INDEX session_summary_key_idx ON ah.session_summary USING btree (agent, session_uid, agent_id);

CREATE INDEX session_summary_session_idx ON ah.session_summary USING btree (session_id);

CREATE INDEX source_file_logical_idx ON ah.source_file USING btree (logical_uid);

CREATE INDEX source_file_ns_idx ON ah.source_file USING btree (namespace, status);

CREATE INDEX subagent_spawn_child_idx ON ah.subagent_spawn USING btree (agent, child_agent_id);

CREATE INDEX subagent_spawn_parent_idx ON ah.subagent_spawn USING btree (parent_session_id);

CREATE INDEX task_ref_key_idx ON ah.task_ref USING btree (task_key);

CREATE INDEX tool_call_error_idx ON ah.tool_call USING btree (error_class, started_at) WHERE (error_class IS NOT NULL);

CREATE INDEX tool_call_name_idx ON ah.tool_call USING btree (tool_name, started_at);

CREATE INDEX tool_call_seq_idx ON ah.tool_call USING btree (session_id, seq);

CREATE INDEX tool_call_session_idx ON ah.tool_call USING btree (session_id, started_at);

CREATE INDEX tool_call_target_host_idx ON ah.tool_call USING btree (started_at) WHERE (meta ? 'target_host'::text);

CREATE INDEX tool_io_call_idx ON ah.tool_io USING btree (agent, call_uid) WHERE (call_uid IS NOT NULL);

CREATE INDEX tool_io_item_idx ON ah.tool_io USING btree (agent, item_uid) WHERE (item_uid IS NOT NULL);

CREATE INDEX tool_io_session_idx ON ah.tool_io USING btree (session_id, ts);

CREATE INDEX tool_op_call_idx ON ah.tool_op USING btree (agent, call_uid) WHERE (call_uid IS NOT NULL);

CREATE INDEX tool_op_seq_idx ON ah.tool_op USING btree (session_id, seq);

CREATE INDEX tool_op_session_idx ON ah.tool_op USING btree (session_id, started_at);

CREATE INDEX turn_started_idx ON ah.turn USING btree (started_at);

ALTER TABLE ONLY ah.artifact
    ADD CONSTRAINT artifact_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.attachment
    ADD CONSTRAINT attachment_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.chunk
    ADD CONSTRAINT chunk_message_id_fkey FOREIGN KEY (message_id) REFERENCES ah.message(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.chunk
    ADD CONSTRAINT chunk_summary_id_fkey FOREIGN KEY (summary_id) REFERENCES ah.session_summary(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.chunk
    ADD CONSTRAINT chunk_tool_call_id_fkey FOREIGN KEY (tool_call_id) REFERENCES ah.tool_call(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.chunk
    ADD CONSTRAINT chunk_tool_op_id_fkey FOREIGN KEY (tool_op_id) REFERENCES ah.tool_op(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.compaction
    ADD CONSTRAINT compaction_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.cost_state
    ADD CONSTRAINT cost_state_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.dirty_session
    ADD CONSTRAINT dirty_session_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.file_touch
    ADD CONSTRAINT file_touch_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES ah.repo(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.file_touch
    ADD CONSTRAINT file_touch_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.git_event
    ADD CONSTRAINT git_event_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES ah.repo(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.git_event
    ADD CONSTRAINT git_event_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.hook_event
    ADD CONSTRAINT hook_event_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.lane
    ADD CONSTRAINT lane_loop_run_id_fkey FOREIGN KEY (loop_run_id) REFERENCES ah.loop_run(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.lane
    ADD CONSTRAINT lane_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.llm_call
    ADD CONSTRAINT llm_call_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.loop_run
    ADD CONSTRAINT loop_run_root_session_id_fkey FOREIGN KEY (root_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.message
    ADD CONSTRAINT message_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.parse_issue
    ADD CONSTRAINT parse_issue_source_id_fkey FOREIGN KEY (source_id) REFERENCES ah.source_file(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.pi_run_response
    ADD CONSTRAINT pi_run_response_source_id_fkey FOREIGN KEY (source_id) REFERENCES ah.source_file(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.rate_limit_sample
    ADD CONSTRAINT rate_limit_sample_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.session_continuation
    ADD CONSTRAINT session_continuation_child_session_id_fkey FOREIGN KEY (child_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.session_continuation
    ADD CONSTRAINT session_continuation_parent_session_id_fkey FOREIGN KEY (parent_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.session_continuation
    ADD CONSTRAINT session_continuation_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.session
    ADD CONSTRAINT session_continued_from_session_id_fkey FOREIGN KEY (continued_from_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.session_embedding
    ADD CONSTRAINT session_embedding_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.session_event
    ADD CONSTRAINT session_event_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.session
    ADD CONSTRAINT session_orchestration_root_session_id_fkey FOREIGN KEY (orchestration_root_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.session
    ADD CONSTRAINT session_parent_session_id_fkey FOREIGN KEY (parent_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.session
    ADD CONSTRAINT session_repo_id_fkey FOREIGN KEY (repo_id) REFERENCES ah.repo(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.session_rollup
    ADD CONSTRAINT session_rollup_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.session
    ADD CONSTRAINT session_root_session_id_fkey FOREIGN KEY (root_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.subagent_spawn
    ADD CONSTRAINT subagent_spawn_child_session_id_fkey FOREIGN KEY (child_session_id) REFERENCES ah.session(id) ON DELETE SET NULL;

ALTER TABLE ONLY ah.subagent_spawn
    ADD CONSTRAINT subagent_spawn_parent_session_id_fkey FOREIGN KEY (parent_session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.task_ref
    ADD CONSTRAINT task_ref_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.tool_call
    ADD CONSTRAINT tool_call_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.tool_io
    ADD CONSTRAINT tool_io_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.tool_op
    ADD CONSTRAINT tool_op_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

ALTER TABLE ONLY ah.turn
    ADD CONSTRAINT turn_session_id_fkey FOREIGN KEY (session_id) REFERENCES ah.session(id) ON DELETE CASCADE;

-- Seed data omitted by the schema-only dump.
INSERT INTO ah.meta (key, value) VALUES ('chunks_reset_at', now()::text) ON CONFLICT (key) DO NOTHING;
INSERT INTO ah.meta (key, value) VALUES ('migration:015_preserve_journal_links.sql', now()::text) ON CONFLICT (key) DO NOTHING;
INSERT INTO ah.meta (key, value) VALUES ('migration:016_tool_output_offset.sql', now()::text) ON CONFLICT (key) DO NOTHING;
INSERT INTO ah.meta (key, value) VALUES ('migration:017_pi_artifact_evidence.sql', now()::text) ON CONFLICT (key) DO NOTHING;
INSERT INTO ah.meta (key, value) VALUES ('migration:018_git_owner_alias.sql', now()::text) ON CONFLICT (key) DO NOTHING;
INSERT INTO ah.meta (key, value) VALUES ('migration:019_message_record_origin.sql', now()::text) ON CONFLICT (key) DO NOTHING;
